### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by rhoconlinux** [mank319/Icon-Set-Forge#5]
Hey, looks really interesting, although I wasn't able to install it to try it out. Any clue? :)
Thanks!

**Comment by 2mac** [comment]
Seems like a build script is in order. @mank319 would you mind writing the compiler flags you use when building this? I'll be happy to write some autotools configs for this and build instructions.

**Comment by mank319** [comment]
Running `qmake-qt4` followed by `make` inside the Code directory should be sufficient.
Please let us know, if it worked for you.

**Comment by rhoconlinux** [comment]
Ok, thanks. I tried, but without success. 
First, I installed the qmake-qt4. After running make I had this output:
<pre>
rho@zenbook:~/Icon-Set-Forge-master/Code$ make
/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h
make: /usr/lib/x86_64-linux-gnu/qt4/bin/uic: Program not found
make: *** [ui_mainwindow.h] Error 127
</pre>

Then I tried installing more qt4 tools by running a <code> sudo apt-get install qt4-designer </code> which solved the program not found error, but didn't run the app. I have this output:

<pre>
rho@zenbook:~/Icon-Set-Forge-master/Code$ make
/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h
g++ -c -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -o iconsetbrowser.o view/iconsetbrowser.cpp
g++ -c -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -o main.o control/main.cpp
g++ -c -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -o mainwindow.o view/mainwindow.cpp
</pre>

**Comment by rhoconlinux** [comment]
Thanks! It worked super!! :+1: 
By the way, I installed two packages. In ubuntu I run <code>sudo apt-get install qmake-qt4 qt4-designer</code>. Then I compiled the program running <code>make</code> and then voilà. :)

Great work guys.

**Comment by rhoconlinux** [comment]
Hi!
Ok, I did an installer. I'm not a programmer, but I'm pretty sure it works (although it lacks of elegance). 
Here is the gist of the sh script.
https://gist.github.com/rhoconlinux/0da826196dd315b21fb4

And here is the line that users should run in order to install the program:

<code>cd /tmp && wget http://ur1.ca/k6mv9 -O isf-install.sh && sh isf-install.sh</code>

after the installation finish, the user should run:

<code>iconsetforge</code>

to start the app. 

Cheers!

ps: I can make an svg icon if you think that could be helpful. With that, another version of the scritp having the .desktop file can be easily implemented.
